# Generated by Django 2.1.1 on 2018-09-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
