# Generated by Django 2.1.1 on 2018-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('desc', models.CharField(default='desc', max_length=500)),
                ('count', models.IntegerField(default=1, max_length=100)),
                ('url', models.CharField(default='url', max_length=500)),
                ('price', models.IntegerField(default=1, max_length=100)),
            ],
        ),
    ]
