# Generated by Django 2.1.1 on 2018-09-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180913_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tovar',
        ),
    ]
