# Generated by Django 2.1.1 on 2018-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_zakaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='idd',
            field=models.CharField(default='id', max_length=100),
        ),
    ]
