# Generated by Django 2.1.1 on 2018-09-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_zakaz_idd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='url', max_length=500)),
                ('usrname', models.CharField(default='user', max_length=100)),
            ],
        ),
    ]
