# Generated by Django 2.1.1 on 2018-10-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20181006_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passw', models.CharField(default='9', max_length=100)),
                ('userr', models.CharField(default='user', max_length=100)),
                ('first_n_last', models.CharField(default='user', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='potok',
        ),
    ]
