# Generated by Django 2.1.1 on 2018-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20181006_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='boo', max_length=500)),
                ('count', models.IntegerField(default=1)),
                ('max_users', models.IntegerField(default=1)),
                ('full_text', models.CharField(default='boo', max_length=500)),
                ('classes', models.CharField(default='dd', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='vending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casenum', models.CharField(default='1', max_length=100)),
                ('tovname', models.CharField(default='case', max_length=500)),
                ('kod', models.CharField(default='123', max_length=500)),
            ],
        ),
    ]
